### ISSUE TITLE
Crash on Stack, VStack, HStack on versions higher than 1.0.0

### ISSUE THREAD

**Issue by LivioGama** [BearStudio/react-native-ficus-ui#38]
https://github.com/BearStudio/react-native-ficus-ui/blob/07ac82f6413ac7a9f0544e3f00cd64ae440ee291/src/components/stack/stack.component.tsx#L105C1-L106C1

I don't really understand why this is happening, but in any React Native Ficus UI versions above 1.0.0 (so starting from 1.1.0), I get a crash on this line indicating an error calling `zIndex` from `undefined`. Probably because props can be undefined in some cases, could you fix it by using `item.props?.zIndex` instead of `item.props.zIndex` please ?

![CleanShot 2024-10-29 at 11 38 21 2@2x](https://github.com/user-attachments/assets/79d0785d-2bc2-4295-92f2-f0cf0c32d29d)

**Comment by ntorionbearstudio** [comment]
@LivioGama Fix is available on new release https://github.com/BearStudio/react-native-ficus-ui/releases/tag/1.3.3
Thanks for your contribution
